### ISSUE TITLE
Перетаскивание блока только за один элемент

### ISSUE THREAD

**Issue by iamsalnikov** [Tuch/angular-dnd#15]
Допустим, что у меня есть такая разметка:

```html
<div id="draggable">
    <div id="drag-control"></div>
</div>
```

Элемент `#draggable`  я делаю перетаскиваемым. Он занимает всю ширину экрана, и высотой 100 пикселей. Внутри него `#drag-control`, который размером 10 на 10 пикселей. Могу ли я сделать так, чтобы элемент `#draggable` перетаскивался **только тогда**, когда мы тащим за `#drag-control`?

**Comment by Tuch** [comment]
Сорри, что так долго небыло ответа. Добавил новую опцию (handle) и обновил примеры:
http://tuch.github.io/angular-dnd/latest/demo/
