### ISSUE TITLE
Issue with dnd-fitted text

### ISSUE THREAD

**Issue by sanyam-j** [Tuch/angular-dnd#19]
1 How to get the font size set by the dnd-fitted with rect model object.
2 When placing only the glyphicons icon inside the div with dnd, its not re-sizing it

**Comment by sanyam-j** [comment]
@Tuch Hey, need your help on this too.

**Comment by Tuch** [comment]
@sanyam-j, can u show example?

**Comment by sanyam-j** [comment]
@Tuch Here it is http://plnkr.co/edit/YWkQP7CxFXmHw9mp5WYm?p=preview

**Comment by sanyam-j** [comment]
@Tuch Hey. Any update on the issue. Please help.

**Comment by Tuch** [comment]
@sanyam-j, hello, sorry for late answer. You can try hack like this http://plnkr.co/edit/STunwonzOXFXYvwgI02F?p=preview, (text options with predefined text size)
