### ISSUE TITLE
dnd-droppable="false" not prevents onDrop event

### ISSUE THREAD

**Issue by Dimanoid** [Tuch/angular-dnd#35]
Please see the example http://embed.plnkr.co/H59foIrIvaVn7nPLM1mO/preview
second container has dnd-droppable="false", it correctly not calls onEnter and onLeave, but onDrop still fired.

**Comment by Tuch** [comment]
@Dimanoid fixed in 0.1.19 version

**Comment by Dimanoid** [comment]
gr8, ty
