### ISSUE TITLE
Is it real use sortable feat. draggable?

### ISSUE THREAD

**Issue by inickolay** [Tuch/angular-dnd#47]
Hi all!
Is it possible to use simultaneously two properties: dnd-sortable and dnd-draggable?

After i try to use them - i'm getting error in console, that says:

> Error: $compile:multidir
Multiple Directive Resource Contention

> **Description**
This error occurs when multiple directives are applied to the same DOM element, and processing them would result in a collision or an unsupported configuration.
>
>To resolve this issue remove one of the directives which is causing the collision.
>
>Example scenarios of multiple incompatible directives applied to the same element include:
>
>Multiple directives requesting isolated scope.
Multiple directives publishing a controller under the same name.
Multiple directives declared with the transclusion option.
Multiple directives attempting to define a template or templateURL.

It's me doing something wrong, or is this not possible?

**P.S.** Sorry for bad English ^_^

**Comment by Tuch** [comment]
Hello, this is not possible. Unfortunately. But u can use dnd-draggable for parent mb?

**Comment by inickolay** [comment]
> Hello, this is not possible. Unfortunately.

This is sad ;(

> But u can use dnd-draggable for parent mb?

Thanks for idea!
