### ISSUE TITLE
It only moves horizontally not vertically

### ISSUE THREAD

**Issue by AlfredGjini** [Tuch/angular-dnd#49]
I add the dnd-draggable directive to a div and it moves perfect in a horizontal way but it doesn't move at all vertically. I'm pretty sure it's an issue with my code but it's been a couple of days now and I can't find it. Can you suggest me what might be the problem?

**Comment by Tuch** [comment]
It can be related with container sizes i guess

**Comment by AlfredGjini** [comment]
thank you, I added dnd-containment="body" and it's working perfectly now. I have another small problem now, I'm using resizing but when I resize I want to keep the aspect ratio (constrain proportions). Is there any way to do this?

**Comment by Tuch** [comment]
I guess you can use hooks like onDrag, or something else
