### ISSUE TITLE
Publish latest to npm

### ISSUE THREAD

**Issue by ab-iman** [Tuch/angular-dnd#53]
Please can we make a new release, and publish the latest to npm? We have only 0.1.24 available there, and we are waiting to take advantage of all of the bug fixes since September.

https://www.npmjs.com/package/angular-dnd-module

Thanks!

**Comment by Tuch** [comment]
@ab-iman updated version to 0.1.25

**Comment by ab-iman** [comment]
Much appreciated; thank you! 👍
